# NLP 2026
# Lab 3: Classification and BERT

Have you ever read a movie review and wondered:

```“Is this review actually positive or negative?” 🤔```

In this lab, you will build your own sentiment analysis tool using Natural Language Processing (NLP)! Your goal is to automatically classify movie reviews into one of two categories:

✅ Positive

❌ Negative

We will approach this as a binary classification task and you will experiment with increasingly powerful methods — from classic machine learning to modern neural networks based on transformers 🚀

### 🎯 Learning Goals ###

By completing this lab, you should be able to:

- Formulate sentiment analysis as a binary classification problem

- Design and evaluate hand-crafted text features

- Implement a Bag-of-Words representation

- Apply and evaluate Logistic Regression and alternative classifiers

- Understand how BERT tokenization and embeddings work

- Extract sentence representations using: ```CLS``` token, mean token pooling

- Compare classical ML and transformer-based methods

- Critically analyze evaluation metrics beyond accuracy 📊



### Score breakdown

| Exercise            | Points |
|---------------------|--------|
| [Exercise 1](#e1)   | 1      |
| [Exercise 2](#e2)   | 5      |
| [Exercise 3](#e3)   | 5      |
| [Exercise 4](#e4)   | 5      |
| [Exercise 5](#e5)   | 5      |
| [Exercise 6](#e6)   | 5      |
| [Exercise 7](#e7)   | 3      |
| [Exercise 8](#e8)   | 6      |
| [Exercise 9](#e9)   | 5      |
| [Exercise 10](#e10) | 5      |
| [Exercise 12](#e12) | 5      |
| [Exercise 13](#e13) | 10     |
| Total               | 60     |

This score will be scaled down to 0.6 and that will be your final lab score.

### 📌 **Instructions for Delivery** (📅 **Deadline: 23/Feb 18:00**, 🎭 *wildcards possible*)

✅ **Submission Requirements**
+ 📄 You need to submit a **notebook** 📓 with the code, appropriate comments and figures in all questions. Make sure to have a mix of code (some explanations needed if not clear what you implement), figures to support the answers or your claims and proper amount of text to explain your reasoning, answer etc.
+ ⚡ Make sure that **all cells are executed properly** ⚙️ and that **all figures/results/plots** 📊 you include in the report are also visible in your **executed notebook**.
+ You can work on Google Collab (or other environments), but you need to make sure that your delivered notebook is executed properly.

✅ **Collaboration & Integrity**
+ 🗣️ While you may **discuss** the lab with others, you must **write your solutions with your group only**. If you **discuss specific tasks** with others, please **include their names** below.
+ 📜 **Honor Code applies** to this lab. For more details, check **Syllabus §7.2** ⚖️.
+ 📢 **Mandatory Disclosure**:
   - Any **websites** 🌐 (e.g., **Stack Overflow** 💡) or **other resources** used must be **listed and disclosed**.
   - Any **GenAI tools** 🤖 (e.g., **ChatGPT**) used must be **explicitly mentioned**.
   - 🚨 **Failure to disclose these resources is a violation of academic integrity**. See **Syllabus §7.3** for details.

## 0. Setup

We first install the scikit-learn library [Scikit-learn](https://scikit-learn.org/stable/). We will use its classification models.

In [3]:
from sympy import false

#pip install -U scikit-learn

We will need [PyTorch](https://pytorch.org/) installed. It is a very popular deep learning library that offers modularized versions of many of the sequence models we discussed in class. It's an important tool that you may want to practice further if you want to dive deeper into NLP, since much of the current academic and industrial research uses it.

Some resources to look further are given below.

* [Documentation](https://pytorch.org/docs/stable/index.html) (We will need this soon)

* [Installation Instructions](https://pytorch.org/get-started/locally/)

* [Quickstart Tutorial](https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html)

The cell below should install the library:

In [4]:
#pip install torch torchvision



The last bit we need is the huggingface transformers library (here is the documentation [https://huggingface.co/docs/transformers/en/index](https://huggingface.co/docs/transformers/en/index)). Transformers are one of the most influential architectures in handling sequences (not only in language). As we discussed in lectures, they excel at taking into account context (which is the salt-and-pepper of NLP) with mechansisms such as self-attetion, which allows them to weigh the importance of different words in a sentence. If you want to know more, revisit the course material (slides and textbook).

We already used huggingface datasets in previous labs and huggingface transformers integrates nicely with that. Apart from the ease of use, huggingface is also providing pre-trained models of different kinds. The list can be found [here](https://huggingface.co/models) ([https://huggingface.co/models](https://huggingface.co/models)). The following line should be enough to install huggingface transformers library:

In [5]:
#pip install transformers

In [6]:
# created this to install libraries ignore this
# %pip install datasets
# %pip install nltk

Here, we import the libraries:

In [7]:
import re
from collections import Counter
from string import punctuation

import datasets
import numpy as np
import torch
import tqdm
import transformers
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from torch.utils.data.dataloader import DataLoader
import string
import collections
from sklearn.metrics import precision_score, recall_score, f1_score
import nltk
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /home/laura/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /home/laura/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

## 1. Loading the Dataset

We will work with the IMDB dataset [https://huggingface.co/datasets/stanfordnlp/imdb](https://huggingface.co/datasets/stanfordnlp/imdb). It contains the reviews and a label that indicates whether the review is positive or not (the neutral reviews have been filtered out). You can read the paper [here](https://aclanthology.org/P11-1015/).

In [8]:
dataset = datasets.load_dataset('stanfordnlp/imdb', split=['train', 'test'])
print(dataset)

[Dataset({
    features: ['text', 'label'],
    num_rows: 25000
}), Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})]


Notice that the dataset has been loaded as a list of two datasets. They are the `train` and `test` splits that we asked for.
We will use the validation subset to tune the parameters. So, let's split the `train` subset and create a `DatasetDict` object:

In [9]:
train_valid_split = dataset[0].train_test_split(5000)
dataset = datasets.DatasetDict({
    'train': train_valid_split['train'].shuffle(),
    'validation': train_valid_split['test'].shuffle(),
    'test': dataset[1].shuffle(),
})
print(dataset)

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 20000
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 5000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
})


We can print several examples from the `train` dataset:

In [10]:
for i in range(5):
    print('i', i)
    print(dataset['train'][i]['text'])
    print(dataset['train'][i]['label'])
    print()

i 0
This is a very light headed comedy about a wonderful family that has a son called Pecker because he use to Peck at his Food. Pecker loves to take all kinds of pictures of the people in a small suburb of Baltimore, Md., and manages to get the attention of a group of photo art lovers from New York City. Pecker has a cute sister who goes simply nuts over SUGAR and is actually an ADDICT, taking spoonfuls of sugar from a bag. There are scenes of men showing off the lumps in their jockey's with grinding movements and gals doing pretty much the same. It is rather hard to keep your mind out of the gutter with this film, but who cares, it is only a film to give you a few laughs at a simple picture made in 1998.
1

i 1
I'm on the opposite end of the previous comment.<br /><br />First of all, I don't think this was intended to be a straight sequel to "The Jerk". I mean, it's not titled "The Jerk 2"... it's "The Jerk, Too", which leads me to believe that while a lot of the character names are 

Let's extract the labels from the dataset. We will use them to train and evaluate our classifiers.

In [11]:
y_train = dataset['train']['label']
print(y_train)
y_valid = dataset['validation']['label']
print(y_valid)

Column([1, 1, 1, 0, 1, ...])
Column([0, 1, 1, 0, 1, ...])


<a name='e1'></a>
#### Exercise 1: Cleaning the text

(1p) In this exercise you should clean the text in the dataset. This is the same step we saw in the previous labs.

If you think this step is not necessary in this use case, you can skip this step, but make sure to justify your decision.

In [12]:
def clean(text):
    """
    Cleans the text
    Args:
        text: a string that will be cleaned

    Returns: the cleaned text

    """

    # Empty text
    if text == '':
        return text

    ### YOUR CODE HERE
    text = re.sub(r'(?<=\d),(?=\d)', '', text) # remove comma between numbers, i.e. 15,000 -> 15000
    text = re.sub(r'([.,!?;:"])', r' \1 ', text) # space out the punctuation (i.e. "hello, world." -> "hello , world .")

    text = text.lower() # Extra step: making everything lowercase
    text = re.sub(r'http\S+', '', text) # Extra step: removes urls starting with https
    text = re.sub(r'#', '', text) # Extra step: removes hashtags

    # eliminate stop words
    text = re.sub(r'\b(a|an|the|and|or|but)\b', '', text)

    # substitute - with white spaces
    text = re.sub(r'-', ' ', text)

    # remove punctuation
    text = re.sub(r'[^\w\s]', '', text)

    text = re.sub(r'\s+', ' ', text) # remove multiple spaces at the end of the cleaning process, as some of the previous steps can introduce double spacing


    ### YOUR CODE ENDS HERE

    return text


def clean_example(example):
    """
    Applies the clean() function to the example from the Dataset
    Args:
        example: an example from the Dataset

    Returns: update example with cleaned 'text' column

    """
    example['text'] = clean(example['text'])
    return example


dataset = dataset.map(clean_example, desc="Cleaning")
print(dataset)

Cleaning:   0%|          | 0/20000 [00:00<?, ? examples/s]

Cleaning:   0%|          | 0/5000 [00:00<?, ? examples/s]

Cleaning:   0%|          | 0/25000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 20000
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 5000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
})


## 2. Hand-crafted Features

<a name='e2'></a>
#### Exercise 2: Hand-crafted features

(5p) Write your own hand-crafted feature extraction function. Include at least these types of features:
- length of the text,
- number of different punctuation characters,
- number of positive and negative words.

In [13]:
### YOUR CODE HERE
# you can define the positive and negative words here

positive = ['good', 'excellent', 'amazing', 'groundbreaking', 'awesome', 'captivating', 'mesmerizing', 'thrilling', 'amazed', 'thrilled', 'awe', 'captivated', 'clever', 'critically acclaimed', 'enjoyable', 'enjoyed', 'cheerful', 'underrated', 'interesting', 'interestingly', 'fantastic', 'brilliant', 'masterpiece', 'delightful', 'delight', 'bingable']
negative = ['bad', 'awful', 'disappointing', 'disappointed', 'mediocre', 'uninteresting', 'inexpressive', 'uninterested', 'unpleasant', 'disgusting', 'disgusted', 'awfully', 'poorly', 'catastrophic', 'boring', 'annoying', 'overrated', 'overhyped', 'unwatchable']



def calculate_features(text):
    features = []
    ### YOUR CODE HERE

    # retrieves the length of the text and adds it as a feature
    length = len(text)
    features.append(length)

    # find set of all possible unique punctutation marks
    punct_chars = set(string.punctuation)
    # find all unique punctuation marks are in the text
    punctuation = [char for char in text if char in punct_chars]
    # count the number of different punctuation marks and add it as a feature
    different_punct = len(punctuation)
    features.append(different_punct)

    # find number of positive words in review and add t as a feature
    n_positive = sum([text.count(word) for word in positive])
    features.append(n_positive)

    n_negative = sum([text.count(word) for word in negative])
    features.append(n_negative)

    pos_neg = n_positive - n_negative
    features.append(pos_neg)

    # tokenizr by whitespace
    words = text.split()
    # calculate average word length and add it as a feaure
    words_len = sum(len(word) for word in words)
    avg_word_len = words_len / len(words)
    features.append(avg_word_len)

    # calculate number of capital letters and add it as a feature
    n_cap_words = sum(1 for word in words if word.isupper() and len(word) > 1)
    features.append(n_cap_words)

    ### YOUR CODE ENDS HERE
    return np.array(features, dtype=float)


### YOUR CODE ENDS HERE

The function below will apply your feature extraction implementation to a specified dataset.

In [14]:
def calculate_features_dataset(dataset, features_fn):
    all_features = []
    for e in tqdm.tqdm(dataset, desc='Extracting features'):
        text = e['text']
        features = features_fn(text)
        all_features.append(features)
    all_features = np.array(all_features, dtype=float)
    return all_features

And we can obtain the features for the `train` and `validation` splits. Later you will need to do the same for the `test` subset.

In [15]:
X_train = calculate_features_dataset(dataset['train'], calculate_features)
X_valid = calculate_features_dataset(dataset['validation'], calculate_features)

Extracting features: 100%|██████████| 5000/5000 [00:00<00:00, 6070.73it/s]


### 2.1 Classification

In this section, we will create and train a logistic regression classifier. We will train it on the `train` subset and evaluate on the `validation` split. Later, you will do a final comparison between methods on the `test` subset, but it is important to avoid it when tuning the methods.

In [16]:
classifier = LogisticRegression(solver='lbfgs', max_iter=1000)
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

Let's check the performance on the training data:

In [17]:
print('Features results: train')
pred_train = classifier.predict(X_train)
print(accuracy_score(y_train, pred_train))

Features results: train
0.6928


... and the validation dataset:

In [18]:
print('Features results: validation')
pred_valid = classifier.predict(X_valid)
print(accuracy_score(y_valid, pred_valid))

Features results: validation
0.6784


<a name='e3'></a>
#### Exercise 3: Improving the features

(5p) Iteratively improve your hand-crafted features. Think about what information from the review might be useful for to predict the rating a person gave to the particular movie. You can also look into the expected format (or range) of features for the classifier.

Document the steps you tried (even if unsuccessful) and how they influenced the metrics. Try at least 3 modifications from your original implementation.

In [19]:
### YOUR CODE HERE
# code improved inside the calculate_features function

### YOUR CODE ENDS HERE

--- YOUR ANSWERS HERE

I first tried adding a feature that calculates the difference between the number of positive and negative words in the review, but this didn't change the accuracy score at all. Probably because that information is already encoded in the number of positive and number of negative words, and adding the difference doesn't add any new information. So the next feature I tried adding was the average word length. This feature increased the accuracy on the validation set. This is likely a useful feature because it can capture the complexity of the language used to describe the movie, which can be an indicator of the review's sentiment. I imagine that people who enjoyed a movie are more likely to put effort into writing a detailed review, however this might not always eb the case since some people are also passionate about writing negative reviews. My next improvement was expanding the positive and negative vocabulary to over double the number of words. I thougt this was most likely the most representative feature in order to determine the sentiment of a review, and I expected it to improve the accuracy score. This change did improve accuracy on both the train set and validation set, but the improvement was not as significant as I expected. Lastly, I extracted the number of words in all caps as a feature, since I thought that this could exprress anger or extreme disappointment. This feature also improved the accuracy score on the train and validation set by a little bit, but not too much. This might be because some people might use all caps to express excitement. The final accuracy on the train set is 0.69115 and on the validation set is 0.6874.

<a name='e4'></a>
#### Exercise 4: Improving the evaluation

(5p) In the previous cells, we only looked at the accuracy of predictions. Investigate which other metrics might be better for our case. You can check the documentation of scikit-learn for evaluation metrics ([https://scikit-learn.org/stable/api/sklearn.metrics.html#classification-metrics](https://scikit-learn.org/stable/api/sklearn.metrics.html#classification-metrics)). Give reasons why the metrics you try can be more informative than raw accuracy score.

Decide which evaluation metric(s) is most suitable for our use-case and give reasons why. Test your features-based classifier and all further classifiers on that metric (apart from the accuracy score).

In [20]:
### YOUR CODE HERE
print('VALIDATION SET')
print('PRECISION')
print(precision_score(y_valid, pred_valid))
print('RECALL')
print(recall_score(y_valid, pred_valid))
print('F1 SCORE')
print(f1_score(y_valid, pred_valid))
print('TRAIN SET')
print('PRECISION')
print(precision_score(y_train, pred_train))
print('RECALL')
print(recall_score(y_train, pred_train))
print('F1 SCORE')
print(f1_score(y_train, pred_train))

### YOUR CODE ENDS HERE

VALIDATION SET
PRECISION
0.6353697749196141
RECALL
0.806530612244898
F1 SCORE
0.7107913669064748
TRAIN SET
PRECISION
0.655
RECALL
0.8211940298507463
F1 SCORE
0.7287417218543046


--- YOUR ANSWERS HERE

we decided to use precision, recall and f1 score as our evaluation metrics because they covers the blindspots of accuracy. Precision measures the proportion of true positives predictions out of all positive predictions, which is useful to avoid false positives. Recall measures the proportion of true positives out of all actual positives, which is useful to avoid false negatives. and the f1 socre is just a combination of precision and recall, which gives us a more balanced view of the model's performance.

## 3. Bag-of-Words Classifier

Similar to the previous lab, we will use the classic bag-of-words representation as one of our embeddings. While it is simple and does not preserve the positions of words, it gives our classifier a lot of useful information.

<a name='e5'></a>
#### Exercise 5: Implementing BOW

(5p) Implement the BOW. In this exercise, we do not give you a rigid structure, so you can conjure your own. The two things your code should produce is the `token_to_id` dictionary, and `bag_of_words()` function that accepts a list of tokens, and the `token_to_id` dictionary while generating the BOW representation as a numpy array.

In [21]:


#### YOUR CODE HERE

MAX_VOCAB_SIZE = 1_000

# The goal is to implement the `bag_of_words(tokens, token_to_id)` function similar to the previous lab.
# You might want to follow the steps:
# - tokenize the `text` column in the dataset,
# - extract the vocabulary from the tokens,
# - limit the vocabulary to `MAX_VOCAB_SIZE`,
# - calculate the `token_to_id` dictionary
# - implement the `bag_of_words(tokens, token_to_id)` function.

token_to_id = {}

def tokenize(text):
    # we use nltk library to tokenize the text downloaded under imports
    return word_tokenize(text)

all_tokens = []
for example in dataset['train']:
    all_tokens.extend(tokenize(example['text']))


counter = collections.Counter(all_tokens)
vocab = [word for word, count in counter.most_common(MAX_VOCAB_SIZE)]
token_to_id = {word: i for i, word in enumerate(vocab)}


def preprocess(example):
    return {'tokens': tokenize(example['text'])}

dataset = dataset.map(preprocess)

def bag_of_words(tokens, token_to_id):
    """
    Creates a bag-of-words representation of the sentence
    Args:
        tokens: a list of tokens
        token_to_id: a dictionary mapping each word to an index in the vocabulary

    Returns:: a numpy array of size vocab_size with the counts of each word in the vocabulary
    """
    bow = np.zeros(len(token_to_id), dtype=int)

    for token in tokens:
        if token in token_to_id:
            idx = token_to_id[token]
            bow[idx] += 1

    return bow


#### YOUR CODE ENDS HERE

Map:   0%|          | 0/20000 [00:00<?, ? examples/s]

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Here, we will use your implemented function to calculate the bag-of-words for each example in the `train` and `validation` subsets.

In [22]:
train_bows = []
for example in tqdm.tqdm(dataset['train'], desc='Calculating test BOWs'):
    train_bows.append(bag_of_words(example['tokens'], token_to_id))
train_bows = np.array(train_bows, dtype=float)

valid_bows = []
for example in tqdm.tqdm(dataset['validation'], desc='Calculating validation BOWs'):
    valid_bows.append(bag_of_words(example['tokens'], token_to_id))
valid_bows = np.array(valid_bows, dtype=float)

Calculating validation BOWs: 100%|██████████| 5000/5000 [00:01<00:00, 3239.52it/s]


Finally, we can train the classifier on the BOW representations and the labels in the `train` split.

In [23]:
classifier = LogisticRegression(solver='lbfgs', max_iter=1000)
print('Training classifier...')
classifier.fit(train_bows, y_train)

Training classifier...


LogisticRegression(max_iter=1000)

Let's evaluate the classifier:

In [24]:
print('BOW results: train')
pred_train = classifier.predict(train_bows)
print('ACCURACY')
print(accuracy_score(y_train, pred_train))
print('PRECISION')
print(precision_score(y_train, pred_train))
print('RECALL')
print(recall_score(y_train, pred_train))

print('BOW results: validation')
pred_valid = classifier.predict(valid_bows)
print('ACCURACY')
print(accuracy_score(y_valid, pred_valid))
print('PRECISION')
print(precision_score(y_valid, pred_valid))
print('RECALL')
print(recall_score(y_valid, pred_valid))

BOW results: train
ACCURACY
0.88295
PRECISION
0.8772633845551532
RECALL
0.8918407960199005
BOW results: validation
ACCURACY
0.8568
PRECISION
0.836046511627907
RECALL
0.8804081632653061


<a name='e6'></a>
#### Exercise 6: Tuning the model

(5p) Try different values for the vocab size. Experiment with adding the hand-crafted features. Test the model on the evaluation metric of your choice (remember to use the validation split).

In [27]:
#### YOUR CODE HERE
sizes = [500, 2000, 5000]
features = True
results = []
for size in sizes:
    # create token ids
    counter = collections.Counter(all_tokens)
    # RENAMED FROM 'size' BC IT WAS OVERWRITING THE VARIABLE IN THE FOR LOOP
    tokens_size = [word for word, count in counter.most_common(size)]
    # APPLIED THE CHANGE HERE TOO BC I THINK THIS IS WHERE THIS VAR WAS SUPPOSED TO GO
    token_to_id = {word: i for i, word in enumerate(tokens_size)}

    train_bows = []
    for example in tqdm.tqdm(dataset['train'], desc='Calculating train BOWs'):
        train_bows.append(bag_of_words(example['tokens'], token_to_id))
    train_bows = np.array(train_bows, dtype=float)

    valid_bows = []
    for example in tqdm.tqdm(dataset['validation'], desc='Calculating validation BOWs'):
        valid_bows.append(bag_of_words(example['tokens'], token_to_id))
    valid_bows = np.array(valid_bows, dtype=float)

    # tested features
    if features:
        X_train = np.hstack([train_bows, calculate_features_dataset(dataset['train'], calculate_features)])
        X_valid = np.hstack([valid_bows, calculate_features_dataset(dataset['validation'], calculate_features)])
    else:
        X_train = train_bows
        X_valid = valid_bows

    clf = LogisticRegression(solver='lbfgs', max_iter=2000)
    clf.fit(X_train, y_train)

    # evaluations
    pred_valid = clf.predict(X_valid)
    acc = accuracy_score(y_valid, pred_valid)
    prec = precision_score(y_valid, pred_valid)
    rec = recall_score(y_valid, pred_valid)
    f1 = f1_score(y_valid, pred_valid)

    results.append({
        # CHANGED FROM 'sizes' to 'size' BC I THINK U MEANT TO PUT THE SIZE OF THE CURRENT ITERATION OF THE LOOP, NOT A LIST OF ALL SIZES
        'vocab_size': size,
        'accuracy': acc,
        'precision': prec,
        'recall': rec,
        'f1': f1
    })

    print(f"Validation Accuracy: {acc:.4f}, F1: {f1:.4f}")

# Show results
print("\nAll results:")
for r in results:
    print(r)


#### YOUR CODE ENDS HERE

Extracting features: 100%|██████████| 5000/5000 [00:01<00:00, 2777.95it/s]
/home/laura/Desktop/uni/NLP labs/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 2000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=2000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Validation Accuracy: 0.8464, F1: 0.8468


Extracting features: 100%|██████████| 5000/5000 [00:01<00:00, 2536.28it/s]


KeyboardInterrupt: 

## 4. BERT Model

For the first part of this lab, we will be using a pre-trained BERT model from Huggingface, namely the [BERT Cased](https://huggingface.co/google-bert/bert-base-cased). You can read the original paper that introduced this model [here](https://aclanthology.org/N19-1423.pdf). This paper has been one of the most cited papers ever (currently having more than 100,000 citations).

We will specify the model name that can be found on the model's card on huggingface (revisit the first link). Make sure to check what other information Huggingface is offering (e.g. how to use the model, limitations, how to inference, etc.).

In [30]:
model_name = 'google-bert/bert-base-cased'

### 4.1 Tokenizer

The models on huggingface come with their own tokenizers. They are loaded separately from the models. We can use [AutoTokenizer](https://huggingface.co/docs/transformers/v4.40.2/en/model_doc/auto#transformers.AutoTokenizer)'s `from_pretrained()` method to load it.

Inspect the output: The loaded object is of `BertTokenizer` class. Check the documentation [here](https://huggingface.co/docs/transformers/en/model_doc/bert#transformers.BertTokenizer).

In [31]:
tokenizer = transformers.AutoTokenizer.from_pretrained(model_name)
print(tokenizer)

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

BertTokenizer(name_or_path='google-bert/bert-base-cased', vocab_size=28996, model_max_length=512, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)


Next, let's see how we can use it to tokenize some text.

In [32]:

print(dataset['test'][0]['text'])
tokenized = tokenizer(dataset['test'][0]['text'], padding=True, return_tensors='pt')
print("---")
print(type(tokenized))
print("---")
print(tokenized)



 mr bean starring legendary rowan atkinson was huge hit during its run in 1990s i probably first saw it when i was around ten shortly after it ended so i was seeing reruns i certainly wasnt much of fan at time didnt see too many episodes i didnt really get into show until my late teens just few years ago which was when i finally watched every episode unlike before it made me laugh many times since then that has always been case during repeat viewings of episodes br br mr bean is mysterious self centred antisocial extremely naive buffoon whose best friend is his teddy he is pretty much isolated from society life is not easy for him as he constantly struggles with very simple things this is because he lacks some fairly basic knowledge has mind of child he finds himself in various kinds of trouble wherever he goes comes up with very bizarre ways to try solve problems he faces not only does he often cause trouble for himself sometimes for other people as well which he often doesnt tend to 

Examine the outputs: The tokenizer returned three things:
- `input_ids` - this is a PyTorch tensor ([https://pytorch.org/docs/stable/tensors.html](https://pytorch.org/docs/stable/tensors.html)) with the indices of our tokens. PyTorch tensors are similar to numpy arrays. They hold data in a multidimensional array or matrix. The difference is that PyTorch tensors can be placed and modified on the GPU which greatly improves the speed of execution.
- `token_type_ids` - this tensor holds the information about the index of the sentence. This has to do with the classification objective from the original paper, where two sentences were given and the model had to predict if they are connected. Because we only included a single sentence, we have only zeros here. We will not be concerned with it in this lab.
- `attention_mask` - holds the mask that the model will use to determine if the tokens in the `input_ids` are the real tokens or *padding*. Padding is a technique used to ensure that all input sequences have the same length. BERT (like many other NLP models) process data in batches and requires each sequence in a batch to have the same length, so sequences that are shorter than the maximum sequence length in the batch are padded with special tokens. In this case, because we only inputted a single sentence, the mask contains only ones. Later you will see examples where this is not the case.

Let's see how exactly the sentence was tokenized and how we can retrieve the original text. Notice that some words have been split into multiple tokens (remember when we discussed sub-word tokenization in class?). Also pay attention to the added special tokens, namely `CLS` and `SEP`:

The `[CLS]` token is a special classification token added at the beginning of every input sequence. It stands for "classification" (daah!) and is used by BERT to aggregate information from the entire sequence. The final hidden state corresponding to this token (after passing through the transformer layers) is used as the aggregate sequence representation for classification tasks. We will use this later in the lab!

The `[SEP]` token is used to separate different segments or sentences within the input sequence. It stands for "separator" (daaah again!).

In [33]:
print(tokenized['input_ids'].shape)
print("---")
print(tokenizer.convert_ids_to_tokens(tokenized['input_ids'][0]))
print("---")
print(len(tokenizer.convert_ids_to_tokens(tokenized['input_ids'][0])))
print("---")
print(tokenizer.decode(tokenized['input_ids'][0]))
print("---")
print(tokenizer.decode(tokenized['input_ids'][0], skip_special_tokens=True))


torch.Size([1, 347])
---
['[CLS]', 'm', '##r', 'bean', 'starring', 'legendary', 'row', '##an', 'at', '##kins', '##on', 'was', 'huge', 'hit', 'during', 'its', 'run', 'in', '1990s', 'i', 'probably', 'first', 'saw', 'it', 'when', 'i', 'was', 'around', 'ten', 'shortly', 'after', 'it', 'ended', 'so', 'i', 'was', 'seeing', 're', '##run', '##s', 'i', 'certainly', 'wasn', '##t', 'much', 'of', 'fan', 'at', 'time', 'didn', '##t', 'see', 'too', 'many', 'episodes', 'i', 'didn', '##t', 'really', 'get', 'into', 'show', 'until', 'my', 'late', 'teens', 'just', 'few', 'years', 'ago', 'which', 'was', 'when', 'i', 'finally', 'watched', 'every', 'episode', 'unlike', 'before', 'it', 'made', 'me', 'laugh', 'many', 'times', 'since', 'then', 'that', 'has', 'always', 'been', 'case', 'during', 'repeat', 'viewing', '##s', 'of', 'episodes', 'br', 'br', 'm', '##r', 'bean', 'is', 'mysterious', 'self', 'centred', 'anti', '##so', '##cial', 'extremely', 'naive', 'b', '##uff', '##oon', 'whose', 'best', 'friend', 'is', 

Tokenizer can process a list of sentences. This will create a batched output with tensor's first dimension corresponding to the batch size (the number of sentences we passed to the tokenizer). Examine the following cell and make sure it makes sense to you.

In [34]:
print(dataset['test'][0:3]['text'])
tokenized = tokenizer(dataset['test'][0:3]['text'], padding=True, return_tensors='pt')
print(tokenized)
print(tokenized['input_ids'].shape)
print(tokenizer.convert_ids_to_tokens(tokenized['input_ids'][0]))
print(len(tokenizer.convert_ids_to_tokens(tokenized['input_ids'][0])))
print(tokenizer.decode(tokenized['input_ids'][0]))
print(tokenizer.decode(tokenized['input_ids'][0], skip_special_tokens=True))


Token indices sequence length is longer than the specified maximum sequence length for this model (754 > 512). Running this sequence through the model will result in indexing errors


[' mr bean starring legendary rowan atkinson was huge hit during its run in 1990s i probably first saw it when i was around ten shortly after it ended so i was seeing reruns i certainly wasnt much of fan at time didnt see too many episodes i didnt really get into show until my late teens just few years ago which was when i finally watched every episode unlike before it made me laugh many times since then that has always been case during repeat viewings of episodes br br mr bean is mysterious self centred antisocial extremely naive buffoon whose best friend is his teddy he is pretty much isolated from society life is not easy for him as he constantly struggles with very simple things this is because he lacks some fairly basic knowledge has mind of child he finds himself in various kinds of trouble wherever he goes comes up with very bizarre ways to try solve problems he faces not only does he often cause trouble for himself sometimes for other people as well which he often doesnt tend t

<a name='e7'></a>
#### Exercise 7: Questions about the tokenizer

Answer the following questions:
- (1p) What is the size of the vocabulary?
- (2p) What are the special tokens apart from `[CLS]` and `[SEP]`? What are their functions?

--- YOUR ANSWERS HERE

the vocab size is 28996

There are three other special tokens:

    [PAD] -The Padding token is used to make all sequences the same length

    [UNK] - The Unkown token is used to indicate a token that is not in the vocabulary

    [MASK] -The Mask token is used during pretraining for MLM

### 4.2 Loading the Model

In this section, we will load and examine the model. We will start with selecting the device we will place the model on. This will be a GPU (if one is available) or a CPU.

Google Colab offers free access to GPU, provided there is availability (also based on quotas which may vary based on your usage and the overall demand on Colab's resources). If you are working locally, then if you don't have a GPU, CPU will be selected. For the first parts of the assignment running on CPU might be okay but when we have to process the dataset a GPU will be necessary.

The following cell will select the device for us.

In [28]:
device = 'cuda:0' if torch.cuda.is_available() else 'cpu'
print(f'Device: {device}')

Device: cpu


Now, let's load the model from huggingface and move it (slowly because it's heavy due to the large number of parameters) on the device from the previous cell (the methods `to()`).

In [35]:
model = transformers.AutoModel.from_pretrained(model_name)
print('loaded on device:', model.device)
model.to(device)
print('moved to device', model.device)
print(model)


model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: google-bert/bert-base-cased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


loaded on device: cpu
moved to device cpu
BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(28996, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (

When loading the model you might have seen the warning about some unexpected weights. This means that the model on huggingface has some additional weights that were downloaded, but our model does not use them. In essence, you can load the same weights (as linked by our `model_name`) to load to different but related models. In our case those would be `BertForMaskedLM` or `BertForNextSentencePrediction` instead of our `BertModel`, which is loaded automatically as the `AutoModel`. Below is a way to load the weights into a different model.

In [ ]:
# transformers.BertForMaskedLM.from_pretrained(model_name)

Next, let's use BERT model for inference. We will tokenize the first sentence of our dataset and pass it to the model. We set `output_hidden_states` to `True` in order to have access to the hidden states of the model. Those represent the latent representations after embedding and transformer layers.

In [36]:
tokenized = tokenizer(dataset['test'][0]['text'], padding=True, return_tensors='pt').to(device)
print(tokenized)
model_output = model(**tokenized, output_hidden_states=True)

{'input_ids': tensor([[  101,   182,  1197, 27528,  3937,  9445,  5105,  1389,  1120,  9615,
          1320,  1108,  3321,  1855,  1219,  1157,  1576,  1107,  3281,   178,
          1930,  1148,  1486,  1122,  1165,   178,  1108,  1213,  1995,  3992,
          1170,  1122,  2207,  1177,   178,  1108,  3195,  1231, 10607,  1116,
           178,  4664,  1445,  1204,  1277,  1104,  5442,  1120,  1159,  1238,
          1204,  1267,  1315,  1242,  3426,   178,  1238,  1204,  1541,  1243,
          1154,  1437,  1235,  1139,  1523, 15050,  1198,  1374,  1201,  2403,
          1134,  1108,  1165,   178,  1921,  2542,  1451,  2004,  6199,  1196,
          1122,  1189,  1143,  4046,  1242,  1551,  1290,  1173,  1115,  1144,
          1579,  1151,  1692,  1219,  9488, 10761,  1116,  1104,  3426,  9304,
          9304,   182,  1197, 27528,  1110,  8198,  2191, 17720,  2848,  7301,
         12562,  4450, 22607,   171,  9435,  6931,  2133,  1436,  1910,  1110,
          1117, 21359, 13617,  1119,  

Examine the next cell and make sure everything makes sense to you. Consult the [documentation](https://huggingface.co/docs/transformers/model_doc/bert#transformers.BertModel.forward) in case of doubt.

In [39]:
print(list(model_output.keys()))
print()
print('pooler_output:')
print(type(model_output['pooler_output']))
print(model_output['pooler_output'].shape)
print()
print('hidden_states:')
print(type(model_output['hidden_states']))
print(len(model_output['hidden_states']))
print(type(model_output['hidden_states'][0]))
print(model_output['hidden_states'][0].shape)
print()
print('last_hidden_state:')
print(type(model_output['last_hidden_state']))
print(model_output['last_hidden_state'].shape)
print('additional info')
print(model.num_parameters())
print(model.config.vocab_size)

['last_hidden_state', 'pooler_output', 'hidden_states']

pooler_output:
<class 'torch.Tensor'>
torch.Size([1, 768])

hidden_states:
<class 'tuple'>
13
<class 'torch.Tensor'>
torch.Size([1, 347, 768])

last_hidden_state:
<class 'torch.Tensor'>
torch.Size([1, 347, 768])
additional info
108310272
28996


<a name='e8'></a>
#### Exercise 8: Questions about the Model

Examine the output of the previous cells. Answer the following questions:
- (1p) What is the number of transformer layers in this model?
- (1p) What is the dimension of the embeddings?
- (1p) What is the hidden size of the FFN in the transformer layer?
- (1p) What is the total number of parameters of the model (hint: check the `num_parameters()` method of the model)?
- (1p) How can you find the vocabulary size from the model?
- (1p) What is the length of the `hidden_states` in the output? Why?

--- YOUR ANSWERS HERE

there are 12 transformer layers + 1 embedding layer, thats why the length of the hidden_states is 13.

the dimension is 768 because that is the shape of the pooler output that will go into the embedding layer

the hidden size of the FFN is 3072 because that is the shape of the intermediate hidden state of the first transformer layer

The number of parameters of the model is 108310272

The vocabulary size can be checked using model.config.vocab_size, and it is 28996

the hidden_states length is 13 because there are 12 transformer layers and 1 embedding layer



## 5. BERT Sentence Embeddings

Having the model loaded and ready we can work on obtaining the sentence embeddings. During the last lab, you averaged the token embeddings. This time we will start with something else. Remember the CLS token? Its hidden representation is often used for classification as a representation of the whole sentence. We will do exactly that.

But first, we have to tokenize the dataset using BERT tokenizer.

<a name='e9'></a>
#### Exercise 9: BERT tokenizing examples

(5p) Fill in the following function to embed the examples (passed as a parameter) using the tokenizer (also a parameter). The function will tokenize a batch of examples, but the tokenizer can handle that, if you remember from the previous section.

In [42]:
def tokenize_text_bert(examples, tokenizer):
    """
    Tokenizes the `sentence` column from the batch of examples and returns the whole output of the tokenizer.
    Args:
        examples: a batch of examples
        tokenizer: the BERT tokenizer

    Returns: the tokenized `sentence` column (returns the whole output of the tokenizer)

    """
    ### YOUR CODE HERE
    tokenized_sentence = tokenizer(examples['text'], padding=True, return_tensors='pt')



    ### YOUR CODE ENDS HERE
    return tokenized_sentence


In [43]:
dataset_tokenized_bert = dataset.map(tokenize_text_bert,
                                     fn_kwargs={'tokenizer': tokenizer},
                                     batched=True,
                                     remove_columns=dataset['train'].column_names,)
print(dataset_tokenized_bert)

Map:   0%|          | 0/20000 [00:00<?, ? examples/s]

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 20000
    })
    validation: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 5000
    })
    test: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 25000
    })
})


<a name='e10'></a>
#### Exercise 10: BERT sentence embeddings by the CLS token

(5p) Implement the following function which calculates the sentence embeddings based on the model output (passed to the function as a parameter). It should take the embedding of the CLS token of last layer.

In [ ]:
def calculate_cls_embeddings(input_batch, model_output):
    """
    Calculates the sentence embeddings of a batch of sentences as the last-layer representation of the CLS token.
    Args:
        input_batch: tokenized batch of sentences (as returned by the tokenizer), contains `input_ids`, `token_type_ids`, and `attention_mask` tensors
        model_output: the output of the model given the `input_batch`, contains `last_hidden_state`, `pooler_output`, `hidden_states` tensors

    Returns: tensor of the hidden states of the CLS token (from the last layer) for each example in the batch

    """

    ### YOUR CODE HERE
    sentence_embeddings = None



    ### YOUR CODE ENDS HERE

    return sentence_embeddings

In [ ]:
text = "The weather is nice today."
tokenized = tokenizer(text, padding=True, return_tensors='pt').to(device)
print(tokenized)
model_output = model(**tokenized, output_hidden_states=True)
print(model_output['last_hidden_state'].shape)
sentence_embedding = calculate_cls_embeddings(tokenized, model_output)
print(sentence_embedding.shape)

In [ ]:
def embed_dataset(dataset, model, sentence_embedding_fn, batch_size=8):
    data_collator = transformers.DataCollatorWithPadding(tokenizer)
    data_loader = DataLoader(dataset, batch_size=batch_size, collate_fn=data_collator)
    sentence_embeddings = []
    with torch.no_grad():
        for batch in tqdm.tqdm(data_loader):
            batch.to(device)
            model_output = model(**batch, output_hidden_states=True)
            batch_sentence_embeddings = sentence_embedding_fn(batch, model_output)
            sentence_embeddings.append(batch_sentence_embeddings.detach().cpu())

    sentence_embeddings = torch.concat(sentence_embeddings, dim=0)
    return sentence_embeddings

In [ ]:
bert_cls_train = embed_dataset(dataset_tokenized_bert['train'], model, calculate_cls_embeddings)
print(bert_cls_train.shape)

bert_cls_valid = embed_dataset(dataset_tokenized_bert['validation'], model, calculate_cls_embeddings)
print(bert_cls_valid.shape)

In [ ]:
classifier = LogisticRegression(solver='lbfgs', max_iter=1000)
print('Training classifier...')
classifier.fit(bert_cls_train, y_train)

In [ ]:
print('BERT train')
pred_train = classifier.predict(bert_cls_train)
print(accuracy_score(y_train, pred_train))

print('BERT valid')
pred_valid = classifier.predict(bert_cls_valid)
print(accuracy_score(y_valid, pred_valid))

You can test the model on the evaluation metric of your choice:

In [ ]:
#### YOUR CODE HERE


#### YOUR CODE ENDS HERE

<a name='e11'></a>
#### Exercise 11: BERT Sentence embeddings by averaging tokens

(5p) Implement embedding sentences by averaging the hidden representations of tokens. Make sure to ignore the special and padding tokens. The padding tokens are indicated by the attention mask. You can find the other special tokens using the tokenizer's attributes such as `tokenizer.sep_token_id`. The function accepts the `layer` parameter. Typically, you would use the hidden representations of the last layer, it might be beneficial for some tasks to use previous layers or an averaged representations of multiple layers.

In [ ]:
### YOUR CODE HERE

def calculate_sentence_embeddings(input_batch, model_output, layer=-1):
    """
    Calculates the sentence embeddings of a batch of sentences as a mean of token representations.
    The representations are taken from the layer of the index provided as a `layer` parameter.
    Args:
        input_batch: tokenized batch of sentences (as returned by the tokenizer), contains `input_ids`, `token_type_ids`, and `attention_mask` tensors
        model_output: the output of the model given the `input_batch`, contains `last_hidden_state`, `pooler_output`, `hidden_states` tensors
        layer: specifies the layer of the hidden states that are used to calculate sentence embedding

    Returns: tensor of the averaged hidden states (from the specified layer) for each example in the batch

    """
    attention_mask = input_batch['attention_mask']
    hidden_states = model_output['hidden_states'][layer]

    ### YOUR CODE HERE
    sentence_embeddings = None




    ### YOUR CODE ENDS HERE

    return sentence_embeddings

### YOUR CODE ENDS HERE

We can test it here:


In [ ]:
text = "The weather is nice today."
tokenized = tokenizer(text, padding=True, return_tensors='pt').to(device)
print(tokenized)
model_output = model(**tokenized, output_hidden_states=True)
print(model_output['last_hidden_state'].shape)
sentence_embedding = calculate_sentence_embeddings(tokenized, model_output)
print(sentence_embedding.shape)

We will embed the sentences and evaluate the model on the `validation` subset.


In [ ]:
bert_sentence_train = embed_dataset(dataset_tokenized_bert['train'], model, calculate_sentence_embeddings)
print(bert_cls_train.shape)

bert_sentence_valid = embed_dataset(dataset_tokenized_bert['validation'], model, calculate_sentence_embeddings)
print(bert_cls_valid.shape)

In [ ]:
classifier = LogisticRegression(solver='lbfgs', max_iter=1000)
print('Training classifier...')
classifier.fit(bert_sentence_train, y_train)

In [ ]:
print('BERT train')
pred_train = classifier.predict(bert_sentence_train)
print(accuracy_score(y_train, pred_train))

print('BERT valid')
pred_valid = classifier.predict(bert_sentence_valid)
print(accuracy_score(y_valid, pred_valid))

Test the model on the evaluation metric of your choice:


In [ ]:
#### YOUR CODE HERE


#### YOUR CODE ENDS HERE

## 6. Testing all methods

In this last section, you will bering together all of what you have done so far in this lab. First, you will find the best classifier. Next, you will evaluate all the models you created so far.

<a name='e12'></a>
#### Exercise 12: Find the best classifier for the models

(5p) Basically, do what the title of the exercise says. Evaluate on the `validation` subset. Try at least two other classifiers (apart from the logistic regression). Comment on the results.

In [ ]:
#### YOUR CODE HERE


#### YOUR CODE ENDS HERE

--- YOUR ANSWERS HERE

<a name='e13'></a>
#### Exercise 13: Evaluating methods on the test set

(10p) Test the models you implemented on the test subset:
- Hand-crafted features,
- BOW,
- BERT model based on the CLS token.

You have the models trained already, so only do evaluation.

Evaluate the performance using the metric(s) of your choice. Make sure to discuss the results. Which model performed best? Is this what you expected?

In [ ]:
#### YOUR CODE HERE


### YOUR CODE ENDS HERE

--- YOUR ANSWERS HERE